os:
  - linux
  - osx

language: cpp

compiler:
  - clang
  - gcc

install:
  - [ $TRAVIS_OS_NAME = linux ] && sudo apt-get install libcppunit-dev || brew install cppunit

script:
  - cmake .
  - make
  - make test
