os:
  - linux
  - osx
language: cpp
compiler:
  - clang
  - gcc

branches:
  except:
    - dev/win32

before_install:
  - bundle install
install:
  - rake cppunit

before_script:
- rake cmake
script:
- rake build
after_success:
- rake test

before_deploy:
- rake package

deploy:
  provider: releases
  api-key:
    secure: PQzn2e5n+1JogEd98+z9PS7Nv+6apIGlsvZWjwahRWZaKREFvRq71E28n0BQb5ZnKoZVGsePXEjIJf1q4Y7P3tVTtyUEa76zSd4nkh7+C6f4r7bb9IzM/gLM00+CbHUUsfbxYfo2KOULTk1/AOLCaGgEbdpbKSRos7VgLOeKX2rjuX+8cEUiEqh/7aDaleuZ1br44twg1kDJLDQimi+HHXyzXUEXMkFUUMI/aAKsvOR6Hzr66Zk2+BkwVYfYmXoP58e3MlIJRNcv5Ecm2K5MDucEYpWehWtKa8/p60LLHUQrZfLI/yaYoofStFdGXWt6r4CEEwY9F5Wu2Z3PzBRZR7cR8ap0E4wyklbuLwmEzZBi8wS3pynSsAu4WcdCAN7b+KkPpPN4/BfweUd6Fjx7WJjwvbj1gD/bh/T79SV6rjrfNemzc6hKT7NoNnuns+jwOu1mMcFAjhXVakEaERbJ6F0Egvib63Ky4O0Fq3vrkJmhPEV+8JYj/v/FgSiofvMtMzFgrjQNNS7vZmirdF9FxvPl3YdPA20HLmn8951fEF83lwjpe9hGqvbgn+rm304dqsP4+86rgrJG10ggvWoE2UjIn+w4ocr6h7nDggunqjMgeqIXipQW9Zvo5SxAWLXl79GX2QrBy2dMv0SuX0aWuct32qbp4ASA0ZYsdK93Y1w=
  file_glob: true
  file: dist/fit*.tgz
  skip_cleanup: true
  on:
    tags: true

